const data = [
  {
    id: 1,
    folder: "/images/thistime/",
    url: "thistime",
    cover: "thistime.webp",
    banner: "thistime.webp",
    title: "This Time",
    title_es: "Esta Vez",
    category: "film",
    year: "",
    genre: "fiction short",
    genre_es: "corto ficción",
    length: "25 mins",
    tags: [
      { en: "Concept Development", es: "Concepto" },
      { en: "Directing", es: "Dirección" },
      { en: "Writing", es: "Guión" },
    ],
    hidden_tags: ["Cän't Wáit"],
    desc: "text \n\nmore text",
    desc_es: "texto",
    img: ["thistime.webp", "thistime_l.jpg", "thistime.webp", "thistime.webp"],
    columnnr: 3,
    video: ["youtube", "16 / 9", ""],
  },
  {
    id: 2,
    folder: "/images/",
    url: "titulo",
    cover: "",
    banner: "",
    title: "Title2",
    title_es: "Título2",
    category: "film",
    year: "",
    genre: "",
    genre_es: "",
    length: "",
    tags: [
      { en: "Photography", es: "Fotografía" },
      { en: "Directing", es: "Dirección" },
      { en: "", es: "" },
      { en: "", es: "" },
    ],
    hidden_tags: [],
    desc: "",
    img: [""],
    columnnr: 2,
    video: ["", ""],
  },
  {
    id: 3,
    folder: "/images/",
    url: "proyecto",
    cover: "",
    banner: "",
    title: "Title3",
    title_es: "Título3",
    category: "photo",
    year: "",
    genre: "",
    genre_es: "",
    length: "",
    tags: [
      { en: "Short", es: "Corto" },
      { en: "Writing", es: "Guión" },
      { en: "", es: "" },
      { en: "", es: "" },
    ],
    hidden_tags: [],
    desc: "",
    img: [""],
    columnnr: 2,
    video: ["", ""],
  },
];
