const data = [
  {
    id: 1,
    folder: "/images/thistime/",
    url: "thistime",
    cover: "thistime.webp",
    banner: "thistime.webp",
    title: "This Time",
    title_es: "Esta Vez",
    category: "film",
    year: "",
    genre: "fiction short",
    genre_es: "corto ficción",
    length: "25 mins",
    tags: [
      { en: "Concept Development", es: "Concepto" },
      { en: "Directing", es: "Dirección" },
      { en: "Writing", es: "Guión" },
    ],
    hidden_tags: ["Cän't Wáit"],
    desc: "text \n\nmore text",
    desc_es: "texto",
    img: ["thistime.webp", "thistime_l.jpg", "thistime.webp", "thistime.webp"],
    columnnr: 3,
    video: ["youtube", "16 / 9", ""],
  },
  {
    id: 2,
    folder: "/images/aliberdade/",
    url: "aliberdade",
    cover: "aliberdade_cover.webp",
    banner: "1-2-1.webp",
    title: "A Liberdade",
    title_es: "A Liberdade",
    category: "film",
    year: "2024",
    genre: "Documentary",
    genre_es: "Documental",
    length: "43 min",
    tags: [
      { en: "Director of Photography", es: "Direccíon de Fotografía" },
      { en: "Colour grading", es: "Etalonaje" },
      { en: "", es: "" },
      { en: "", es: "" },
    ],
    hidden_tags: [],
    desc: "text \n\nmore text",
    desc_es:
      "Un documental de retrato íntimo y etnográfico que tiene lugar en la Costa da Morte, Galicia. \n\nSe centra en dos percebeiras: la más joven y la más mayor actualmente. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat dolor nec lacus venenatis, at euismod mi finibus. Ut interdum nulla et leo imperdiet eleifend. Nunc ut venenatis massa. Aenean quis dignissim est, vitae sagittis quam. Phasellus placerat congue orci, vel iaculis ligula vulputate id. Praesent ut nunc purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. \n\nDirector de Fotografía. Etalonaje. \n\nEstreno en Early Bird International Student Film Festival en Sofia, 2025.",
    img: [
      "6.webp",
      // "5.webp",
      "5.jpg",
      "5-1.webp",
      "3.webp",
      "4-3.webp",
      "5-2.webp",
      "2.webp",
      "1.webp",
      "2-3.webp",
      "2-2.webp",
      "3-2.webp",
      "1-2-1.webp",
      "3-3.webp",
      "4-3.webp",
      "4-1.webp",
      "6-2.webp",
      "6-3.webp",
    ],
    columnnr: 3,
    video: ["youtube", "16 / 9", "https://www.youtube.com/embed/D1JwxALW42I"],
    // https://www.youtube.com/embed/D1JwxALW42I
  },
  {
    id: 3,
    folder: "/images/",
    url: "proyecto",
    cover: "",
    banner: "",
    title: "Title3",
    title_es: "Título3 largo es toda un frase drámatica",
    category: "photo",
    year: "",
    genre: "",
    genre_es: "",
    length: "",
    tags: [
      { en: "Short", es: "Corto" },
      { en: "Writing", es: "Guión" },
      { en: "", es: "" },
      { en: "", es: "" },
    ],
    hidden_tags: [],
    desc: "",
    img: [""],
    columnnr: 2,
    video: ["", ""],
  },
  {
    id: 4,
    folder: "/images/thistime/",
    url: "thistime",
    cover: "thistime.webp",
    banner: "thistime.webp",
    title: "This Time",
    title_es: "Esta Vez",
    category: "film",
    year: "",
    genre: "fiction short",
    genre_es: "corto ficción",
    length: "25 mins",
    tags: [
      { en: "Concept Development", es: "Concepto" },
      { en: "Directing", es: "Dirección" },
      { en: "Writing", es: "Guión" },
    ],
    hidden_tags: ["Cän't Wáit"],
    desc: "text \n\nmore text",
    desc_es: "texto",
    img: ["thistime.webp", "thistime_l.jpg", "thistime.webp", "thistime.webp"],
    columnnr: 3,
    video: ["youtube", "16 / 9", ""],
  },
  {
    id: 5,
    folder: "/images/aliberdade/",
    url: "aliberdade2",
    cover: "aliberdade_cover.webp",
    banner: "1-2-1.webp",
    title: "A Liberdade",
    title_es: "A Liberdade",
    category: "film",
    year: "2024",
    genre: "Documentary",
    genre_es: "Documental",
    length: "43 min",
    tags: [
      { en: "Director of Photography", es: "Direccíon de Fotografía" },
      { en: "Colour grading", es: "Etalonaje" },
      { en: "", es: "" },
      { en: "", es: "" },
    ],
    hidden_tags: [],
    desc: "text \n\nmore text",
    desc_es:
      "Un documental de retrato íntimo y etnográfico que tiene lugar en la Costa da Morte, Galicia. \n\nSe centra en dos percebeiras: la más joven y la más mayor actualmente. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat dolor nec lacus venenatis, at euismod mi finibus. Ut interdum nulla et leo imperdiet eleifend. Nunc ut venenatis massa. Aenean quis dignissim est, vitae sagittis quam. Phasellus placerat congue orci, vel iaculis ligula vulputate id. Praesent ut nunc purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. \n\nDirector de Fotografía. Etalonaje. \n\nEstreno en Early Bird International Student Film Festival en Sofia, 2025.",
    img: [
      "6.webp",
      // "5.webp",
      "5.jpg",
      "5-1.webp",
      "3.webp",
      "4-3.webp",
      "5-2.webp",
      "2.webp",
      "1.webp",
      "2-3.webp",
      "2-2.webp",
      "3-2.webp",
      "1-2-1.webp",
      "3-3.webp",
      "4-3.webp",
      "4-1.webp",
      "6-2.webp",
      "6-3.webp",
    ],
    columnnr: 2,
    video: ["youtube", "16 / 9", "https://www.youtube.com/embed/D1JwxALW42I"],
    // https://www.youtube.com/embed/D1JwxALW42I
  },
  {
    id: 6,
    folder: "/images/",
    url: "proyecto",
    cover: "",
    banner: "",
    title: "Title3",
    title_es: "Título3 largo es toda un frase drámatica",
    category: "photo",
    year: "",
    genre: "",
    genre_es: "",
    length: "",
    tags: [
      { en: "Short", es: "Corto" },
      { en: "Writing", es: "Guión" },
      { en: "", es: "" },
      { en: "", es: "" },
    ],
    hidden_tags: [],
    desc: "",
    img: [""],
    columnnr: 2,
    video: ["", ""],
  },
];
